### ISSUE TITLE
UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 408: illegal multibyte sequence

### ISSUE THREAD

**Issue by choi-seung-min** [flavors/django-graphiql-debug-toolbar#11]
i tried to install this but "UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 408: illegal multibyte sequence" error comes out
here's error logs
`ERROR: Command errored out with exit status 1:
     command: 'c:\users\user\pycharmprojects\eva-server\venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-eo8z9066\\django-graphiql-debug-toolbar\\setup.py'"'"'; __file__='"'"'C:\\Users
\\user\\AppData\\Local\\Temp\\pip-install-eo8z9066\\django-graphiql-debug-toolbar\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info -
-egg-base 'C:\Users\user\AppData\Local\Temp\pip-install-eo8z9066\django-graphiql-debug-toolbar\pip-egg-info'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-eo8z9066\django-graphiql-debug-toolbar\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-eo8z9066\django-graphiql-debug-toolbar\setup.py", line 26, in <module>
        long_description='\n\n'.join(get_long_description()),
      File "C:\Users\user\AppData\Local\Temp\pip-install-eo8z9066\django-graphiql-debug-toolbar\setup.py", line 12, in get_long_description
        yield f.read()
    UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 408: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by fangaofeng** [comment]
I met this UnicodeDecodeError: 'gbk' codec can't decode byte 0xa5 in position 410: illegal multibyte sequence

**Comment by ulgens** [comment]
What is your Python version / how did you install it? Also, i'd suggest to work in a virtualenv. Windows is still a wild beast when it comes to Python.
